### ISSUE TITLE
 Thanks for providing code folding function!

### ISSUE THREAD

**Issue by x64bugreport** [Byzero512/hexraysIDAplus#1]
I want to trigger the fold to use shortcut keys. The most common mouse click operation is the highlight function, which can cause conflicts. I hope you can accept my suggestion. thank you very much. I look forward to you continuing to update the project.

**Comment by x64bugreport** [comment]
Currently, I have modified the mouse click to prevent conflicts with the highlight plugin. It works well, thank you very much! Hope you can continue to update this project. Looking forward to completing the following work!
1.code match: TODO
2.simplify c++ decompiled code: TODO

case hxe_keyboard: 
	{
		vdui_t* vu = va_arg(va, vdui_t*);
		int keyCode = va_arg(va, int);
		int shift_state = va_arg(va, int);
		if (keyCode == 'm' || keyCode == 'M')
		{
			cfunc_t* cfunc = vu->cfunc;
			reFoldCode(vu);
		}
		break;
	}

**Comment by x64bugreport** [comment]
Regarding the simplification of C++, it is recommended to refer to the following items. At the same time, I hope you divide these plug-ins into different plug-ins, and try not to write these functions in one plug-in. thank you very much.
https://github.com/zyantific/REtypedef
https://github.com/nihilus/RECPP

**Comment by Byzero512** [comment]
1. the key 'w' will be used to fold the code and I dont want to remove double click. I dont find out how double click will be conflict with highlight function.
2.  about simplifying c++, it will need a long time to finish.
3. it will not be divided into different plugins for maintaining and promoting easier.

**Comment by x64bugreport** [comment]
Thank you for your reply and hope everything goes well.
